name: Feature Report
description: File a feature report
title: "[Feature]: "
labels: ["feature"]
projects: ["khantzawhein/2"]
assignees:
  - khantzawhein
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: What is your name?
      placeholder: ex. Srettha Thavisin
    validations:
      required: false
  - type: markdown
    attributes:
      values: Thanks for taking time to fill out this bug report!  
  - type: dropdown
    id: typeofreq
    attributes:
      label: Type of request?
      description: Select the type of your request
      options:
        - New Feature
        - New Idea
      default: 0
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What is the OS you want to suggest?
      multiple: true
      options:
        - Windows
        - Mac OS
        - Ubuntu
  - type: textarea
    id: what-happened
    attributes:
      label: What are the details of your suggestion?
      description: Explain what do you want
      placeholder: Tell us what you see!
      value: "Feature details!"
    validations:
      required: true
  
